# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'iOSonRails' do
  pod 'AFNetworking', '~> 2.0'
 # pod 'RestKit', '~> 0.20.0'
  pod 'SVPullToRefresh' 
  pod 'SDWebImage', '~>3.6'
  pod 'UICKeyChainStore'
  pod 'MMPlaceHolder'
  pod 'MagicalRecord'
  pod 'MONActivityIndicatorView'
  pod 'Reachability', '~> 3.2'
end

target 'iOSonRailsTests' do

end

